#!/usr/bin/env bash
alias xsc="xclip -selection clipboard"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

#!/usr/bin/env bash
alias esc="$HOME/.config/sway/config"
alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"

alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias ebp="$VIM $DOTFILES/.zsh_profile"
alias etc="$VIM $DOTFILES/rc-files/$USER/.tmux.conf"
alias bp="dotFileInstall && source ~/.zshrc"
alias evrc="$VIM $DOTFILES/rc-files/$USER/.vimrc"
alias enrc="nvim $DOTFILES/rc-files/$USER/init.vim --cmd \"cd $DOTFILES/rc-files/$USER/init.vim\""
alias yolo="git push origin master --force --no-verify"
alias eirc="nvim $XDG_CONFIG_HOME/i3/i3config"
alias cvrc="cat $DOTFILES/vimrc/.vimrc"
alias dotFileInstall="$DOTFILES/install"

alias pjson="python -mjson.tool"
alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"
alias timeplus="~/dotfiles/apps/time_plus_30"
alias echotime="~/dotfiles/apps/echo_time"

alias cnpm="cat ~/.npmrc"
alias rnpm='rm ~/.npmrc'